packages:
  - apps/*
  - packages/*
minimumReleaseAgeExclude:
  - '@vitest/mocker@5.0.2'
  - '@vitest/spy@5.0.2'
  - viem@2.56.9
  - vitest@5.0.2
  - framer-motion@13.4.4
  - motion-dom@13.4.4
  - motion@13.4.4
