// Copies contract ABIs from Foundry's build output into packages/core as typed `as const` modules.
// Run after `forge build` (pnpm build does both).
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
const out = join(root, "contracts", "out");

const contracts = [
  { file: "Tipoff.sol/Tipoff.json", name: "tipoffAbi" },
  { file: "MockUSDC.sol/MockUSDC.json", name: "mockUsdcAbi" },
];

const body = contracts
  .map(({ file, name }) => {
    const { abi } = JSON.parse(readFileSync(join(out, file), "utf8"));
    return `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;`;
  })
  .join("\n\n");

writeFileSync(
  join(root, "packages", "core", "src", "abi.ts"),
  `// Generated by scripts/export-abi.ts from contracts/out. Do not edit.\n\n${body}\n`,
);
console.log(`abi: wrote ${contracts.map((c) => c.name).join(", ")}`);
